//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acter()
        {
            this.Zhanr_actera = new HashSet<Zhanr_actera>();
            this.Career_actera = new HashSet<Career_actera>();
            this.Personazh_and_Acter = new HashSet<Personazh_and_Acter>();
            this.Spravochnay_informacia = new HashSet<Spravochnay_informacia>();
            this.Syprygi = new HashSet<Syprygi>();
            this.Foto = new HashSet<Foto>();
        }
    
        public int id { get; set; }
        public string Name_acter { get; set; }
        public string Familia_acter { get; set; }
        public string Rost { get; set; }
        public Nullable<System.DateTime> Date_of_birth_acter { get; set; }
        public Nullable<int> id_Znak_zodiaka { get; set; }
        public string Vozrast { get; set; }
        public int id_Mesto_rozhenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zhanr_actera> Zhanr_actera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Career_actera> Career_actera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personazh_and_Acter> Personazh_and_Acter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spravochnay_informacia> Spravochnay_informacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Syprygi> Syprygi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual Mesto_rozhenia Mesto_rozhenia { get; set; }
        public virtual Znak_zodiaka Znak_zodiaka { get; set; }
    }
}
