//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sheldon_Childhood_AEntities : DbContext
    {
        public Sheldon_Childhood_AEntities()
            : base("name=Sheldon_Childhood_AEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acter> Acter { get; set; }
        public virtual DbSet<Career> Career { get; set; }
        public virtual DbSet<Career_actera> Career_actera { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Informacia_about_film> Informacia_about_film { get; set; }
        public virtual DbSet<Interesniy_fact> Interesniy_fact { get; set; }
        public virtual DbSet<Mesto_rozhenia> Mesto_rozhenia { get; set; }
        public virtual DbSet<Nacionalnost> Nacionalnost { get; set; }
        public virtual DbSet<Oblozhka> Oblozhka { get; set; }
        public virtual DbSet<Otzivi> Otzivi { get; set; }
        public virtual DbSet<Personazh> Personazh { get; set; }
        public virtual DbSet<Personazh_and_Acter> Personazh_and_Acter { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Proisxozhenie> Proisxozhenie { get; set; }
        public virtual DbSet<Proizvodstvo> Proizvodstvo { get; set; }
        public virtual DbSet<Proizvodstvo_filma> Proizvodstvo_filma { get; set; }
        public virtual DbSet<Religia> Religia { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Seria_and_Sezon> Seria_and_Sezon { get; set; }
        public virtual DbSet<Something> Something { get; set; }
        public virtual DbSet<Spravochnay_informacia> Spravochnay_informacia { get; set; }
        public virtual DbSet<Svazannie_filmi> Svazannie_filmi { get; set; }
        public virtual DbSet<Syprygi> Syprygi { get; set; }
        public virtual DbSet<Vid> Vid { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Zhanr> Zhanr { get; set; }
        public virtual DbSet<Zhanr_actera> Zhanr_actera { get; set; }
        public virtual DbSet<Znak_zodiaka> Znak_zodiaka { get; set; }
    }
}
