//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int id { get; set; }
        public Nullable<int> id_Acter { get; set; }
        public Nullable<int> id_Personazh { get; set; }
        public byte[] Fotos { get; set; }
    
        public virtual Acter Acter { get; set; }
        public virtual Personazh Personazh { get; set; }
    }
}
