//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informacia_about_film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informacia_about_film()
        {
            this.Proizvodstvo_filma = new HashSet<Proizvodstvo_filma>();
        }
    
        public int id { get; set; }
        public System.DateTime Date_of_vixod_in_USA { get; set; }
        public System.DateTime Date_of_vixod_in_Russia { get; set; }
        public int Kolichestvo_sezonov { get; set; }
        public int Kolichestvo_seria { get; set; }
        public int id_Zhanr { get; set; }
        public string Opisanie_seriala { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodstvo_filma> Proizvodstvo_filma { get; set; }
        public virtual Zhanr Zhanr { get; set; }
    }
}
