//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oblozhka
    {
        public int id { get; set; }
        public int id_Svazannie_filmi { get; set; }
        public byte[] Oblozhkas { get; set; }
    
        public virtual Svazannie_filmi Svazannie_filmi { get; set; }
    }
}
