//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int id { get; set; }
        public string Familia { get; set; }
        public string Names { get; set; }
        public int id_Roles { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
