//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodstvo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodstvo()
        {
            this.Proizvodstvo_filma = new HashSet<Proizvodstvo_filma>();
        }
    
        public int id { get; set; }
        public string Name_proizvodstvo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodstvo_filma> Proizvodstvo_filma { get; set; }
    }
}
