//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodstvo_filma
    {
        public int id { get; set; }
        public int id_Informacia_about_film { get; set; }
        public int id_Proizvodstvo { get; set; }
    
        public virtual Informacia_about_film Informacia_about_film { get; set; }
        public virtual Proizvodstvo Proizvodstvo { get; set; }
    }
}
