//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Svazannie_filmi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Svazannie_filmi()
        {
            this.Oblozhka = new HashSet<Oblozhka>();
        }
    
        public int id { get; set; }
        public string Name_Svazannie_filmi { get; set; }
        public int id_Vid { get; set; }
        public string Promezhytok_Svazannie_filmi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oblozhka> Oblozhka { get; set; }
        public virtual Vid Vid { get; set; }
    }
}
