//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syprygi
    {
        public int id { get; set; }
        public int id_Acter { get; set; }
        public string Name_Syprygi { get; set; }
        public string Familia_Syprygi { get; set; }
        public string Kolichestvo_detey { get; set; }
        public string Razvod { get; set; }
    
        public virtual Acter Acter { get; set; }
    }
}
