//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int id { get; set; }
        public byte[] Videos { get; set; }
        public int id_Seria_and_Sezon { get; set; }
    
        public virtual Seria_and_Sezon Seria_and_Sezon { get; set; }
    }
}
