//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sheldon.база
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhanr_actera
    {
        public int id { get; set; }
        public int id_Acter { get; set; }
        public int id_Zhanr { get; set; }
    
        public virtual Acter Acter { get; set; }
        public virtual Zhanr Zhanr { get; set; }
    }
}
